# group_vars/all.yml - Cleaned for single-node, official Wazuh EDR automation
wazuh_version: "4.12"
wazuh_gpg_key: "https://packages.wazuh.com/key/GPG-KEY-WAZUH"
wazuh_repo_url: "https://packages.wazuh.com/4.x/apt/"

# Node/host config (localhost only)
wazuh_manager_node_name: "wazuh-1"
wazuh_indexer_node_name: "node-1"
wazuh_dashboard_node_name: "dashboard"

# Service ports
wazuh_manager_port: 1514
wazuh_indexer_port: 9200
wazuh_dashboard_port: 443

# Credentials (default, change after install)
wazuh_admin_user: "admin"
wazuh_admin_password: "admin"
wazuh_indexer_user: "admin"
wazuh_indexer_password: "admin"

# Certs
wazuh_certificates_tar: "/tmp/wazuh-certificates.tar"

# System
ansible_python_interpreter: "/usr/bin/python3"
ansible_become: true
ansible_become_method: sudo