---
# main.yml - Core tasks for Wazuh Server role
# Installs and configures Wazuh Server with secure defaults, handlers, and templates
- name: Install Wazuh repository GPG key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present
  tags: [install, server]

- name: Add Wazuh repository
  apt_repository:
    repo: 'deb https://packages.wazuh.com/4.x/apt/ stable main'
    state: present
  tags: [install, server]

- name: Install Wazuh manager
  apt:
    name: wazuh-manager
    state: present
    update_cache: yes
  tags: [install, server]

- name: Deploy ossec.conf from template
  template:
    src: ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: '0640'
  notify: restart wazuh services
  tags: [config, server]

- name: Validate ossec.conf is not empty
  stat:
    path: /var/ossec/etc/ossec.conf
  register: ossec_conf_stat

- name: Fail if ossec.conf is empty
  fail:
    msg: "ossec.conf is empty! Check your template and variables."
  when: ossec_conf_stat.stat.size == 0

- name: Ensure wazuh-manager is running
  service:
    name: wazuh-manager
    state: started
    enabled: yes
  register: wazuh_service
  tags: [service, server]
  ignore_errors: yes

- name: Print wazuh-manager status and logs if failed
  shell: |
    systemctl status wazuh-manager.service
    journalctl -xeu wazuh-manager.service | tail -n 20
  when: wazuh_service is failed
  register: wazuh_debug
  changed_when: false
  failed_when: false

- name: Show wazuh-manager troubleshooting output
  debug:
    var: wazuh_debug.stdout_lines
  when: wazuh_service is failed
