
# --- Wazuh Server Assisted Installation (Single Node) ---
- name: Download Wazuh installation assistant
  get_url:
    url: https://packages.wazuh.com/4.12/wazuh-install.sh
    dest: /tmp/wazuh-install.sh
    mode: '0755'
  tags: [install, server]

- name: Ensure wazuh-install-files.tar is present
  stat:
    path: /tmp/wazuh-install-files.tar
  register: wazuh_install_files_tar
  tags: [install, server]

- name: Fail if wazuh-install-files.tar is missing
  fail:
    msg: "wazuh-install-files.tar is missing in /tmp. Please copy it from the certificate generation step."
  when: not wazuh_install_files_tar.stat.exists
  tags: [install, server]

- name: Run Wazuh installation assistant for single-node server
  command: bash /tmp/wazuh-install.sh --wazuh-server wazuh-1
  args:
    chdir: /tmp
  register: wazuh_install_result
  tags: [install, server]
  changed_when: "'Wazuh server is now successfully installed' in wazuh_install_result.stdout or wazuh_install_result.rc == 0"

# --- Optionally disable Wazuh repo after install for security ---
- name: Disable Wazuh repository after install (recommended)
  lineinfile:
    path: /etc/apt/sources.list.d/wazuh.list
    regexp: '^deb '
    line: '#deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main'
    state: present
  tags: [install, server]


