# Test OpenSearch configuration for troubleshooting
cluster.name: wazuh-cluster
node.name: wazuh-indexer-1

# Network settings
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# SSL is disabled - provide empty paths to satisfy plugin requirements
plugins.security.ssl.http.enabled: false
plugins.security.ssl.transport.enabled: false
plugins.security.ssl.http.pemcert_filepath: ""
plugins.security.ssl.http.pemkey_filepath: ""
plugins.security.ssl.transport.pemcert_filepath: ""
plugins.security.ssl.transport.pemkey_filepath: ""
plugins.security.ssl.transport.pemtrustedcas_filepath: ""
plugins.security.ssl.http.pemtrustedcas_filepath: ""

# Performance settings
bootstrap.memory_lock: false
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer
path.config: /etc/wazuh-indexer

# Discovery settings
discovery.type: single-node

# Security plugin configuration
plugins.security.allow_unsafe_democertificates: true
plugins.security.allow_default_init_securityindex: true
plugins.security.nodes_dn_dynamic_config_enabled: true
plugins.security.audit.type: internal_opensearch
plugins.security.enable_snapshot_restore_privilege: true
plugins.security.check_snapshot_restore_privilege: true
plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
plugins.security.system_indices.enabled: true
plugins.security.system_indices.permissions.enabled: true

# Performance tuning
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 10%
indices.fielddata.cache.size: 10%
