# docker-compose.yml - Semaphore (Ansible UI) deployment
version: '3.8'
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_DB_PATH: /etc/semaphore/database.boltdb
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_PLAYBOOK_PATH: /playbooks
      SEMAPHORE_PROJECT_NAME: "IaC EDR"
    volumes:
      - semaphore_data:/etc/semaphore
      - ../playbooks:/playbooks:ro
      - ../inventory:/inventory:ro
      - ../roles:/roles:ro
      - ../files:/files:ro
    restart: unless-stopped
volumes:
  semaphore_data:
