
# --- Ensure required packages are installed ---
- name: Install required system packages
  apt:
    name:
      - debconf
      - adduser
      - procps
      - gnupg
      - apt-transport-https
    state: present
    update_cache: yes

# --- Add Wazuh GPG key using official keyring method ---
- name: Download and import Wazuh GPG key
  shell: |
    curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | \
      gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && \
      chmod 644 /usr/share/keyrings/wazuh.gpg
  args:
    creates: /usr/share/keyrings/wazuh.gpg

# --- Add Wazuh repository using signed-by ---
- name: Add Wazuh Indexer repository (official method)
  copy:
    dest: /etc/apt/sources.list.d/wazuh.list
    content: |
      deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

# --- Install Wazuh Indexer ---
- name: Install Wazuh Indexer
  apt:
    name: wazuh-indexer
    state: present
    update_cache: yes

# --- Certificate Generation (Wazuh Certs Tool) ---
- name: Download wazuh-certs-tool.sh
  get_url:
    url: https://packages.wazuh.com/4.12/wazuh-certs-tool.sh
    dest: /tmp/wazuh-certs-tool.sh
    mode: '0755'

- name: Render config.yml for certs tool (always runs)
  template:
    src: config.yml.j2
    dest: /tmp/config.yml
    mode: '0644'

- name: Generate Wazuh certificates
  command: bash /tmp/wazuh-certs-tool.sh -A -i /tmp/config.yml
  args:
    chdir: /tmp

- name: Create certificates directory for indexer
  file:
    path: /etc/wazuh-indexer/certs
    state: directory
    owner: wazuh-indexer
    group: wazuh-indexer
    mode: '0755'

- name: Move and rename node certificate and key to indexer certs dir
  shell: |
    mv /tmp/wazuh-certificates/node-1.pem /etc/wazuh-indexer/certs/indexer.pem
    mv /tmp/wazuh-certificates/node-1-key.pem /etc/wazuh-indexer/certs/indexer-key.pem
    mv /tmp/wazuh-certificates/root-ca.pem /etc/wazuh-indexer/certs/root-ca.pem
    mv /tmp/wazuh-certificates/admin.pem /etc/wazuh-indexer/certs/admin.pem
    mv /tmp/wazuh-certificates/admin-key.pem /etc/wazuh-indexer/certs/admin-key.pem
    chmod 500 /etc/wazuh-indexer/certs
    chmod 400 /etc/wazuh-indexer/certs/*
    chown -R wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/certs
  args:
    executable: /bin/bash

- name: Remove wazuh-certificates.tar for security
  file:
    path: /tmp/wazuh-certificates.tar
    state: absent

# --- Cluster initialization ---
- name: Initialize Wazuh Indexer cluster
  command: /usr/share/wazuh-indexer/bin/indexer-security-init.sh


