---
# 00_setup_infra.yml - Main playbook for Wazuh EDR deployment
# Deploys Wazuh Server, Indexer, Dashboard, and Agents with environment segregation and dry-run support
- name: Setup Wazuh EDR Infrastructure
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - common
    - wazuh_indexer
    - wazuh_server
    - wazuh_dashboard
    - wazuh_agents
  tags: [core, all]

  handlers:
    - name: Restart all Wazuh services
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - wazuh-manager
        - wazuh-indexer
        - wazuh-dashboard
        - filebeat
      listen: "restart all wazuh services"
