---
- name: Deploy Wazuh EDR Full Stack (All-in-One)
  hosts: all
  connection: local
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - wazuh_indexer
    - wazuh_server
    - wazuh_dashboard
    - wazuh_agents
